version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MovieAPI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9kdrr4xqa7qy"
s3_prefix = "MovieAPI"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

