AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: API Gateway Lambda service to retrieve movie information form DB
Resources:
  MovieDetails:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: API Gateway Lambda service to retrieve movie information form DB
      MemorySize: 128
      Timeout: 3
      Role: "arn:aws:iam::921119069545:role/service-role/MovieProcessor-role-iyqbuy2g"
      Events:
        Api1:
          Type: Api
          Properties:
            Path: "/details/{id+}"
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: "/recommended/{id+}"
            Method: GET
      Environment:
        Variables:
          DB_HOST: moviedb.c3tgw2putqdy.us-east-1.rds.amazonaws.com
          DB_NAME: moviesdb
          DB_PASSWORD: 4IMJsW8jF2p0maOhOQLN
          DB_USER: movieadmin
      Tags:
        "lambda-console:blueprint": microservice-http-endpoint
