version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MovieLexProcessor"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9kdrr4xqa7qy"
s3_prefix = "MovieLexProcessor"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
