//@ts-check

const countries = [
  'Germany',
  'France',
  'Italy',
  'Australia',
  'Mexico',
  'Cuba',
  'Finland',
  'Hungary',
  'Argentina',
  'Czechoslovakia',
  'India',
  'Poland',
  'Armenia',
  'Bahamas',
  'Switzerland',
  'Bhutan',
  'Algeria',
  'Afghanistan',
  'Vietnam',
  'Romania',
  'Palestinian Territory',
  'Kenya',
  'Uganda',
  'Indonesia',
  'Chile',
  'United Kingdom',
  'Belgium',
  'Hong Kong',
  'Japan',
  'Ireland',
  'Taiwan',
  'Denmark',
  'Cambodia',
  'Sweden',
  '2013',
  'Luxembourg',
  'Colombia',
  'Senegal',
  'Lebanon',
  'Bosnia and Herzegovina',
  'Thailand',
  'Haiti',
  'Israel',
  'Jamaica',
  'Tajikistan',
  'Georgia',
  'Singapore',
  'United Arab Emirates',
  'Congo',
  'United States',
  'China',
  'South Africa',
  'Canada',
  'Iran',
  'Austria',
  'Spain',
  'Brazil',
  'Czech Republic',
  'Soviet Union',
  'Fiji',
  'Cameroon',
  'Greece',
  'Ukraine',
  'Belarus',
  'Croatia',
  'Estonia',
  'Netherlands',
  'New Zealand',
  'Peru',
  'South Korea',
  'Russia',
  'Bulgaria',
  'Egypt',
  'Iceland',
  'Norway',
  'Aruba',
  'Serbia',
  "Cote D'Ivoire",
  'Philippines',
  'Ecuador',
  'Mongolia',
  'Uruguay',
  'Turkey',
  'Ghana'
];

module.exports.findCountry = (country) => {
  return countries.find((k) => k.toLowerCase() === country.toLowerCase());
};

/**
 * Checks if its a valid date
 * @param {Date} d
 */
module.exports.checkDate = (d) => {
  // @ts-ignore
  return d instanceof Date && !isNaN(d);
};
