AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Lambda function for MovieBOT LEX Service
Resources:
  MovieProcessor:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: lambda/
      Description: Lambda function for MovieBOT LEX Service
      MemorySize: 128
      Timeout: 3
      Role: "arn:aws:iam::921119069545:role/service-role/MovieProcessor-role-iyqbuy2g"
      Environment:
        Variables:
          DB_KEY: rds-secret
          SPELLCHECK_KEY: spellcheck
